import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Header } from '@/components/header'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Ignite Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.className} flex min-h-screen flex-col items-start justify-center bg-zinc-900 text-zinc-100 antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
